name: build

on:
  push:
    branches:
      - "main"
      - "testing-ci"
      - "feature/*"
    tags-ignore:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.2
    - name: Run tests
      run: make test
    - name: Lint programs
      uses: golangci/golangci-lint-action@v5
      with:
        version: v1.58
        skip-pkg-cache: true
        skip-build-cache: true
        skip-go-installation: true
